config/routes.rb
Plans::Application.routes.draw do

  namespace :admin do
    resources :accounts
    resources :autofingers
    resources :avail_links
    resources :board_votes
    resources :custom_stylesheets
    resources :display_preferences
    resources :interfaces
    resources :main_boards
    resources :opt_links
    resources :permissions
    resources :plans
    resources :poll_choices
    resources :poll_questions
    resources :poll_votes
    resources :secrets
    resources :styles
    resources :sub_boards
    resources :systems
    resources :tentative_accounts
    resources :viewed_secrets

    root to: "accounts#index"
  end

  mount Forem::Engine, :at => '/notes'

  # For more information on routing, see http://guides.rubyonrails.org/routing.html.

  # just remember to delete public/index.html.
  root controller: 'plans', action: 'show', id: 'plans'

  resources :plans do
    collection do
      get :set_autofinger_level
      put :mark_level_as_read
      get :search, as: 'search'
      get :planwatch, as: :recently_updated
      get :genesis, as: :recently_created
    end
    member do
      get :edit
      put :update
      get :show, as: 'read'
      put :set_autofinger_subscription
    end
  end

  resources :secrets

  resources :preferences, only: [:index]
  namespace :preferences do
    resource :account, controller: :account_details, only: [:show, :update]
    resource :display, controller: :display, only: [:show, :update]
    resources :blocks, controller: :blocks, only: [:index, :create, :destroy] do
      get :about, on: :collection
    end
  end

  resource :account_session, only: [:new, :create, :destroy]

  resources :accounts do
    collection do
      get :new
      post :create
      get :confirm
      post :resend_confirmation_email
      get :reset_password
    end
  end

  resources :pages do
    get :faq
  end

  resources :password_resets, except: [:destroy, :show, :index]

  get '/register' => 'accounts#new', :as => :register
  get '/login' => 'account_sessions#new', :as => :login
  delete '/logout' => 'account_sessions#destroy', :as => :logout

  # Placeholder routes until we build the real things
  get "/" => "plans#show", as: :polls
  get "/" => "plans#show", as: :random_plan

  # adding default route as lowest priority
  # match '/:controller(/:action(/:id))'
end

app/models/account_session.rb
class AccountSession < Authlogic::Session::Base
  generalize_credentials_error_messages true
end

app/controllers/account_sessions_controller.rb
class AccountSessionsController < ApplicationController
  skip_before_filter :require_user, only: [:new, :create]
  layout false

  def new
    @session = AccountSession.new
  end

  def create
    @session = AccountSession.new account_session_params
    if @session.save
      session[:autofinger_level] = 1
      account = @session.record
      account.login = Time.now
      account.save!
      redirect_to root_path
    else
      render action: :new
    end
  end

  def destroy
    current_account_session.destroy
    @current_account = nil
    @current_account_session = nil
    flash[ :notice] = "You've been logged out."
    redirect_to login_path
  end

  def account_session_params
    params.require(:account_session).permit(:username, :password, :password_confirmation)
  end
end

app/views/account_sessions/new.haml
%html{:dir=>"ltr"}
  %head
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html", :charset=>"utf-8"}
    %title GrinnellPlans
    = csrf_meta_tag
    :css
      .field_with_errors { display: inline; }
    = javascript_include_tag :account_sessions
  %body
    .left
      %br
      %br
      %table{:cellpadding=>0, :width=>"100%"}
        %tr
          %td{:colspan=>2, :align=>"center"}
            =image_tag "logo.png"
        %tr.boxes
          %td.boxes{:colspan=>2, :align=>"center"}
            =form_for @session, :url => account_session_path do |f|
              =f.label :"Username : "
              =f.text_field :username
              %br
              =f.label :"Password : "
              =f.password_field :password
              %br
              =f.submit "Login"
              =f.hidden_field "js_test_value",:value => "off"
              :javascript
                document.getElementById("account_js_test_value").value = "on";
              -if @session.errors.messages[:base]
                .error_message= @session.errors.messages[:base][0]
            %p=link_to("Forgot your password?", new_password_reset_path)
        %tr
          %td{:colspan=>2, :align=>"center"}
            %br
            %br
            Need a plan?
            =link_to "Register", register_path
            if you have an @grinnell.edu email address.
            %br
            %span{:style=>"font-size:0.7em"}
              Otherwise
              =mail_to "grinnellplans@gmail.com", "email us"
              Alumni, please include your @alumni.grinnell.edu forwarding address (which you can get
              =link_to "here", "http://www.alumniconnections.com/olc/pub/GRN/permanentemail.html"
              ) and grad year.
            %br
            %br
            What is plans?
            =link_to "GrinnellPlans FAQ", "pages/faq.html"
            %br
            Email
            =mail_to "grinnellplans@gmail.com"
            with questions or concerns.
            %br
            %br
            %br
            %br
            %font{:size=>"-1", :face=>"verdana"}
              %i This site is not owned by, operated by, or officially  affiliated with Grinnell College, Grinnell, IA.
    %hr
    %center
    %p.legalese
      Use of the GrinnellPlans service means you have accepted the
      =link_to "GrinnellPlans Terms of Service", "http://www.grinnellplans.com/tos/"
      agreement. If you do not accept and abide by this agreement, you may not use GrinnellPlans. This agreement is subject to change without notice, so you should periodically review the most up-to-date version.