config/routes.rb
Plans::Application.routes.draw do

  namespace :admin do
    resources :accounts
    resources :autofingers
    resources :avail_links
    resources :board_votes
    resources :custom_stylesheets
    resources :display_preferences
    resources :interfaces
    resources :main_boards
    resources :opt_links
    resources :permissions
    resources :plans
    resources :poll_choices
    resources :poll_questions
    resources :poll_votes
    resources :secrets
    resources :styles
    resources :sub_boards
    resources :systems
    resources :tentative_accounts
    resources :viewed_secrets

    root to: "accounts#index"
  end

  mount Forem::Engine, :at => '/notes'

  # For more information on routing, see http://guides.rubyonrails.org/routing.html.

  # just remember to delete public/index.html.
  root controller: 'plans', action: 'show', id: 'plans'

  resources :plans do
    collection do
      get :set_autofinger_level
      put :mark_level_as_read
      get :search, as: 'search'
      get :planwatch, as: :recently_updated
      get :genesis, as: :recently_created
    end
    member do
      get :edit
      put :update
      get :show, as: 'read'
      put :set_autofinger_subscription
    end
  end

  resources :secrets

  resources :preferences, only: [:index]
  namespace :preferences do
    resource :account, controller: :account_details, only: [:show, :update]
    resource :display, controller: :display, only: [:show, :update]
    resources :blocks, controller: :blocks, only: [:index, :create, :destroy] do
      get :about, on: :collection
    end
  end

  resource :account_session, only: [:new, :create, :destroy]

  resources :accounts do
    collection do
      get :new
      post :create
      get :confirm
      post :resend_confirmation_email
      get :reset_password
    end
  end

  resources :pages do
    get :faq
  end

  resources :password_resets, except: [:destroy, :show, :index]

  get '/register' => 'accounts#new', :as => :register
  get '/login' => 'account_sessions#new', :as => :login
  delete '/logout' => 'account_sessions#destroy', :as => :logout

  # Placeholder routes until we build the real things
  get "/" => "plans#show", as: :polls
  get "/" => "plans#show", as: :random_plan

  # adding default route as lowest priority
  # match '/:controller(/:action(/:id))'
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  include PlanTextFormatting

  belongs_to :account, foreign_key: :user_id
  before_save :clean_text
  after_update :set_modified_time
  after_update :update_autofingers
  alias_attribute :generated_html, :plan
  # validates_presence_of :account
  validates_length_of :plan, maximum: 16_777_215, message: 'Your plan is too long'
  validates_length_of :edit_text, maximum: 16_777_215, message: 'Your plan is too long'

  # TODO: Consider migrating user_id to userid, like everythig else
  def userid
    user_id
  end

  def generated_html
    read_attribute(:plan).html_safe
  end

  def clean_text
    self.generated_html = clean_and_format edit_text
  end

  private

  def set_modified_time
    account.changed = Time.now
    account.save!
  end

  def update_autofingers
    account.interests_from_others.update_all(updated: 1)
  end
end

app/controllers/admin/plans_controller.rb
module Admin
  class PlansController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Plan.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Plan.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/plan_controller.rb
class PlanController < ApplicationController
  
  def edit
   @plan = current_account.plan
  end
  
  def update
    @plan = current_account.plan
    @plan.edit_text = params[:plan][:edit_text]
    if @plan.save
      redirect_to :action=>:read, :username => @plan.account.username
    else
      render :action => "edit"
    end
  end
  
  def read
      @account = Account.find_by_username(params[:username])
      if @account.blank?
        #search
      else
          # mark as read
          autofinger = Autofinger.where(:owner=>current_account.userid, :interest=> @account.userid ).first
          unless autofinger.blank?
            autofinger.updated = '0'
            autofinger.readtime = Time.now
            autofinger.save!
          end
      end
  end
  
  def search
    
  end
  
  def mark_as_read
    
  end
  
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def edit
    @plan = current_account.plan
  end

  def update
    @plan = current_account.plan
    @plan.edit_text = unsafe_params[:plan][:edit_text]
    if @plan.save
      flash[:notice] = "Plan updated successfully"
      redirect_to read_plan_path(id: @plan.account.username)
    else
      render action: 'edit'
    end
  end

  def show
    username = params[:id]
    @account = Account.find_by_username(username)
    if @account.blank?
      redirect_to action: :search, id: username
    else
      active_blocks = Block.where(blocking_user_id: @account.userid)
        .where(blocked_user_id: current_account.userid)
      @plantext = if active_blocks.empty?
                    @account.plan.generated_html
                  else
                    "[#{@account.username}] has enabled the block feature. This plan is not available."
                  end
      @viewing_self = username == current_account.username
      @block = Block.where(blocking_user_id: current_account.userid)
        .where(blocked_user_id: @account.userid)
        .first
      Autofinger.mark_plan_as_read(current_account.userid, @account.userid)
    end
  end

  def mark_level_as_read
    Autofinger.mark_level_as_read(current_account.userid, unsafe_params[:level])
    redirect_to unsafe_params[:return_to]
  end

  def set_autofinger_level
    session[:autofinger_level] = unsafe_params[:level]
    redirect_to unsafe_params[:return_to]
  end

  def search
    q = params[:q]
    @account = Account.find_by_username(q)
    if !@account.blank? && params[:follow_usernames]
      redirect_to read_plan_path(id: @account.username)
    elsif q.present?
      matching_plans = Plan.where("edit_text LIKE ?", "%#{q}%").joins(:account).order('accounts.username').includes(:account)
      @results = matching_plans.inject([]) do |results, plan|
        matches = []
        last = 0
        text = Sanitize.clean(plan.plan, elements: ["br"])
        while (i = text.index(q, last)).present?
          start_pos = text.index(/\s/, [0, i - 100].max)
          end_pos = text.index(/\s/, i + q.length)
          end_pos = [end_pos, i + q.length + 120].compact.min
          matches << { text: text.slice(start_pos, end_pos).html_safe, pos: [i - start_pos, i + q.length - start_pos] }
          last = end_pos
        end
        results << { plan: plan, matches: matches }
      end
    end
  end

  def planwatch
    @hours = if params[:hours].to_i < 1 then 12 else params[:hours].to_i end
    blocks = (Block.where(blocking_user_id: current_account.userid).pluck(:blocked_user_id) +
              Block.where(blocked_user_id: current_account.userid).pluck(:blocking_user_id)).uniq
    @plans = Account.where(changed: (Time.now - @hours.hours)..Time.now)
                    .order(changed: :desc)
                    .where.not(userid: blocks)
  end

  def genesis
    @days = if params[:days].to_i < 1 then 5 else params[:days].to_i end
    @plans = Account.where(created: (Time.now - @days.days)..Time.now).order(created: :desc)
  end

  def set_autofinger_subscription
    owner = current_account
    interest = Account.find_by_username(unsafe_params[:id])
    autofinger = owner.interests_in_others.find_or_create_by(interest: interest.id)
    success = autofinger.update_attributes(priority: unsafe_params[:priority])
    if success
      if unsafe_params[:priority] == '0'
        notice = 'User was removed from your autoread list.'
      else
        notice = "User is now on your autoread list with priority level of #{unsafe_params[:priority]}."
      end
    else
      notice = "Could not change autoread priority. If this happens more than once, contact the Plans admins at grinnellplans@gmail.com."
    end
    redirect_to :back, notice: notice
  end
end

app/views/plans/edit.html.haml
- content_for :head do
  = javascript_include_tag :plans

#editform
  =form_for @plan, :url => {:action=>:update, :controller=>:plans } do |f|
    =f.text_area :edit_text, :rows=>"14", :onkeyup=>"javascript:checkPlanLength()"
    %br
    #edit_fill_meter
      .fill_bar
        .full_amount
      .fill_percent
        0%
    =f.submit

app/views/plans/genesis.html.haml
= form_tag({}, method: "get") do
  = label_tag "days", "Plans created in the past:"
  = number_field_tag "days", @days, min: 1, max: 100
  = label_tag "days", "days"
  = submit_tag "Go"
%ul
  - @plans.each do |p|
    %li
      = link_to p.username, p.username
      = p.created_date.strftime "%k:%M %p, %a %B %e"

app/views/plans/planwatch.html.haml
= form_tag({}, method: "get") do
  = label_tag "hours", "Plans updated in the past:"
  = number_field_tag "hours", @hours, min: 1, max: 100
  = label_tag "hours", "hours"
%ul
  - @plans.each do |p|
    %li
      = link_to p.username, p.username
      = p.changed_date.strftime "%k:%M %p, %a %B %e"

app/views/plans/search.html.haml
= form_tag main_app.search_plans_path, method: :get do
  %div{:class=>"form_prompt textinput"}
    = text_field_tag :q, ""
    = button_tag "Search", {:class=>"submitinput"}

%ul#search_results
  - if !@results.nil? && @results.blank?
    = info_message do
      No matches found.
  - elsif @results.present?
    - each_with_list_classes(@results) do |result, classes|
      %li{ class: classes }
        .result_user_group
          = link_to result[:plan].account.username, main_app.read_plan_path(result[:plan].account.username), class: "planlove"
          %span= result[:matches].count
          %ul.result_sublist
            - each_with_list_classes(result[:matches]) do |match|
              %li{ class: classes }
                - output = match[:text].insert(match[:pos][1], "</b>").insert(match[:pos][0], "<b>")
                %span= (Sanitize.clean output, elements: ["b", "br"]).html_safe

app/views/plans/show.html.haml
.plan
  #header
    %ul
      %li.username
        %span.title
          Username
        %span.value
          =@account.username
      %li.lastupdated
        %span.title
          Last Updated:
          / TODO 2 date formats
        %span.value
          %span.long
            =l @account.changed_date unless  @account.changed_date.nil?
          %span.short
            =l @account.changed_date unless  @account.changed_date.nil?
      %li.lastlogin
        %span.title
          Last login:
        %span.value
          %span.short
            =@account.login
          %span.long
            =@account.login
      %li.planname
        %span.title
          Name:
        %span.value
          =@account.pseudo

.plan_text
  = @plantext

.autofinger-control
  = form_tag set_autofinger_subscription_plan_path, method: :put do
    = radio_button_tag :priority, 0
    = label_tag 'priority_0', 'X'
    = radio_button_tag :priority, 1
    = label_tag 'priority_1', 1
    = radio_button_tag :priority, 2
    = label_tag 'priority_2', 2
    = radio_button_tag :priority, 3
    = label_tag 'priority_3', 3
    = submit_tag 'Save'

- if !@viewing_self
  - if @block
    .block-control
      = form_tag preferences_block_path(@account.userid), method: :delete do
        = submit_tag 'Unblock this user'
  - else
    .block-control
      = form_tag preferences_blocks_path, method: :post do
        = hidden_field_tag 'target', @account.userid
        = submit_tag 'Block this user'